# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Admin.create([
  { :email => "eric@base10creations.com", :encrypted_password => "$2a$10$q/Wuxq0tEK7gFMQBj24vEOhlukpCCwL1d1I2XnN2TlT3oQNkrQD92", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-08-20 04:49:54", :last_sign_in_at => "2013-08-20 04:49:54", :current_sign_in_ip => "68.107.107.6", :last_sign_in_ip => "68.107.107.6", :created_at => "2013-08-20 04:49:54", :updated_at => "2013-08-20 04:49:54" },
  { :email => "k.tyksinski@martinfurniture.com", :encrypted_password => "$2a$10$Ye4UtLQu04UGV5kQEjfBXurXFTVmj1lagxaGix60qahqfvMy1CW4G", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-08-20 04:51:28", :last_sign_in_at => "2013-08-20 04:51:28", :current_sign_in_ip => "68.107.107.6", :last_sign_in_ip => "68.107.107.6", :created_at => "2013-08-20 04:51:28", :updated_at => "2013-08-20 04:51:28" },
  { :email => "c.takara@martinfurniture.com", :encrypted_password => "$2a$10$Wl71wiprrx5RSmYMJ1V8k.dqYwhG38OiIhi395Fx.sc9DdIBbPupG", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => "2013-08-20 15:14:30", :sign_in_count => 2, :current_sign_in_at => "2013-08-20 15:14:31", :last_sign_in_at => "2013-08-20 04:52:17", :current_sign_in_ip => "216.70.241.26", :last_sign_in_ip => "68.107.107.6", :created_at => "2013-08-20 04:52:17", :updated_at => "2013-08-20 15:14:31" }
], :without_protection => true )



Brand.create([
  { :name => "kathy-ireland-home-by-martin", :title => "kathy ireland™ Home by Martin", :created_at => "2013-08-05 05:51:56", :updated_at => "2013-08-05 05:51:56" },
  { :name => "martin-home-furnishings", :title => "Martin Home Furnishings", :created_at => "2013-08-05 05:52:14", :updated_at => "2013-08-05 05:52:14" }
], :without_protection => true )



Carousel.create([
  { :name => nil, :title => nil, :page_id => 1, :created_at => "2013-08-05 05:10:20", :updated_at => "2013-08-05 05:10:20" }
], :without_protection => true )



Category.create([
  { :name => "accessories", :title => "Accessories", :created_at => "2013-08-05 05:11:37", :updated_at => "2013-08-05 05:11:37" },
  { :name => "entertainment", :title => "Entertainment", :created_at => "2013-08-05 05:11:50", :updated_at => "2013-08-05 05:11:50" },
  { :name => "occasional", :title => "Occasional", :created_at => "2013-08-05 05:12:02", :updated_at => "2013-08-05 05:12:02" },
  { :name => "office", :title => "Office", :created_at => "2013-08-05 05:12:22", :updated_at => "2013-08-05 05:12:22" }
], :without_protection => true )



Ckeditor::Asset.create([
  { :data_file_name => nil, :data_content_type => nil, :data_file_size => nil, :assetable_id => nil, :assetable_type => nil, :type => nil, :width => nil, :height => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Ckeditor::AttachmentFile.create([
  { :data_file_name => nil, :data_content_type => nil, :data_file_size => nil, :assetable_id => nil, :assetable_type => nil, :type => "Ckeditor::AttachmentFile", :width => nil, :height => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Ckeditor::Picture.create([
  { :data_file_name => nil, :data_content_type => nil, :data_file_size => nil, :assetable_id => nil, :assetable_type => nil, :type => "Ckeditor::Picture", :width => nil, :height => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Collection.create([
  { :name => "beaumont", :title => "Beaumont", :created_at => "2013-08-05 05:28:00", :updated_at => "2013-08-08 01:10:38", :description => "<p>Fine craftsmanship and elegant design radiate warmth and reliability. Featuring maple veneers, antique style drawer pulls and a port finish, the Beaumont collection offers classic Louis Philippe style details and superb craftsmanship.</p>\r\n" },
  { :name => "bradley", :title => "Bradley", :created_at => "2013-08-05 05:28:38", :updated_at => "2013-08-08 01:11:19", :description => "<p>Inspired by the kathy ireland Home&trade; Americana Style Guide&trade;, Bradley is the point where classic design meets modern convenience. This transitional home entertainment collection features hardwood solids with cherry veneers and satin nickel hardware.</p>\r\n" },
  { :name => "california-bungalow", :title => "California Bungalow", :created_at => "2013-08-05 05:29:06", :updated_at => "2013-08-08 01:12:46", :description => "<p>Inspired by the kathy ireland Home&trade; Americana Style Guide&trade; and the early 20th century Arts and Crafts movement, California Bungalow office furniture utilizes sharp lines and iron hardware to produce a simple and functional design. California Bungalow features a classic brown mission finish and is hand-rubbed with lacquer to enhance the richness of natural wood grain.</p>\r\n" },
  { :name => "carlton", :title => "Carlton", :created_at => "2013-08-05 05:30:56", :updated_at => "2013-08-08 04:23:31", :description => "<p>Inspired by the kathy ireland Home&trade; Architectural Style Guide&trade;, Carlton boasts modern architectural flare with clean lines and a clear bourbon finish. Complementing any d&eacute;cor, Carlton is a perfect addition to any home.</p>\r\n" },
  { :name => "concord", :title => "Concord", :created_at => "2013-08-05 05:31:28", :updated_at => "2013-08-08 04:23:48", :description => "<p>Inspired by the kathy ireland Home&trade; Architectural Style Guide&trade;, The stately design of the Concord collection brings a lasting look of sophistication and function to any office environment. Concord features picture frame detailing, satin nickel hardware and a chestnut finish.</p>\r\n" },
  { :name => "contemporary", :title => "Contemporary", :created_at => "2013-08-05 05:31:55", :updated_at => "2013-08-08 04:24:38", :description => "<p>An original Martin Home Furnishings collection, Contemporary is a simple and functional collection. Each piece is finished with multiple-step hand rubbed lacquer, and the case pieces have well-defined bull-nose solid red oak moldings and drawer fronts. The genuine plane slice red oak veneers carefully layered over engineered wood core, combined with ball bearing glides ensure that this collection will stand the test of time.</p>\r\n" },
  { :name => "crescent", :title => "Crescent", :created_at => "2013-08-05 05:32:26", :updated_at => "2013-08-08 04:25:44", :description => "<p>Inspired by the kathy ireland Home&trade; Architectural Style Guide&trade;, Crescent&#39;s graceful structural design will bring charm to any living room. Gentle scoops and contemporary nickel hardware grace sliding door fronts. Expertly crafted of poplar solids and maple veneers, Crescent is available in a bright white, onyx black or cognac finishes.</p>\r\n" },
  { :name => "empire", :title => "Empire", :created_at => "2013-08-05 05:33:29", :updated_at => "2013-08-08 04:26:21", :description => "<p>Inspired by the kathy ireland Home&trade; Architectural Style Guide&trade;, Empire encompasses simplicity and minimalism. Curved picture frame molding, diamond shaped satin nickel hardware, and a deep java finish create a distinctive transitional look.</p>\r\n" },
  { :name => "fremont", :title => "Fremont", :created_at => "2013-08-05 05:35:24", :updated_at => "2013-08-08 04:27:37", :description => "<p>Expertly crafted of select hardwoods and birch veneers, Fremont has a warm chestnut finish and brushed nickel hardware. This transitional group features half-round molding accents and clean architectural lines. The television consoles have a modern breakfront design and offer ample storage space for all of your electronics and accessories.</p>\r\n" },
  { :name => "fulton", :title => "Fulton", :created_at => "2013-08-05 05:36:19", :updated_at => "2013-08-08 04:27:06", :description => "<p>Inspired by the kathy ireland Home&trade; Architectural Style Guide&trade;, Fulton is a soft modern collection that blends traditional design elements like crown molding and picture frame detailing with contemporary influences like clean lines, satin nickel hardware and a rich espresso finish. Bring the best of both design worlds in to your home with the Fulton home office collection, a true design solution for living.</p>\r\n" },
  { :name => "gravity", :title => "Gravity", :created_at => "2013-08-05 05:37:31", :updated_at => "2013-08-08 04:28:05", :description => "<p>Black glass and caramel stained ash veneers blend modern design and timeless sophistication. Gravity boasts sturdy construction and strikingly handsome design. The asymmetric console offers ample media storage behind modern sliding glass doors.</p>\r\n" },
  { :name => "hudson-street", :title => "Hudson Street", :created_at => "2013-08-05 05:37:49", :updated_at => "2013-08-08 04:28:48", :description => "<p>Inspired by the kathy ireland Home&trade; Architectural Style Guide&trade;, Hudson Street is a contemporary collection with clean lines and a classic onyx black finish complemented by brushed nickel hardware. The simplicity of this entertainment furniture collection makes it an easy and comfortable addition to the home. Constructed with hardwood solids and veneers, this collection is built to stand the test of time.</p>\r\n" },
  { :name => "huntington", :title => "Huntington", :created_at => "2013-08-05 05:38:24", :updated_at => "2013-08-08 04:29:16", :description => "<p>Inspired by the kathy ireland Home&trade; Americana Style Guide&trade;, Huntington is a transitional furniture design with crafted of &nbsp;hardwood solids and veneers. Vertical fluting, dentil molding and light distressing add character and aesthetic appeal. Huntington Club is a great addition to any home and will surely last for generations to come. Huntington is available in vibrant cherry, wheat or burnish finishes.</p>\r\n" },
  { :name => "infinity", :title => "iNfinity", :created_at => "2013-08-05 05:38:54", :updated_at => "2013-08-08 04:31:00", :description => "<p>Inspired by the kathy ireland Home&trade; Architectural Style Guide&trade;, iNfinity is well-suited for today&#39;s small home office. Its sleek modern design and sturdy construction will make it a centerpiece of any home. Equipped with wire management or a power center, the technology friendly desks make organizing and connecting electronics a breeze. The contemporary design features tapered legs and a two&ndash;tone finish. Choose between the bright white or onyx black coupled with a rich bourbon finish and accented by satin nickel hardware.</p>\r\n" },
  { :name => "kensington", :title => "Kensington", :created_at => "2013-08-05 05:39:25", :updated_at => "2013-08-08 04:31:27", :description => "<p>Inspired by &nbsp;the kathy ireland Home&trade; Architectural Style Guide&trade; and Biedermeier style, the Kensington collection is comfortably contemporary, showcasing a warm fruitwood finish and contrasting black cove and black bead molding. The tops have reversed diamond matched veneers with a black inlaid border. The posts of the cases are quarter-round and the drawers are accented by half-round molding and ash colored drawer pulls. Kensington is crisp and contemporary without seeming out of place in traditional settings because of the warm finish and understated design elements.</p>\r\n" },
  { :name => "kyoto", :title => "Kyoto", :created_at => "2013-08-05 05:39:45", :updated_at => "2013-08-08 04:32:07", :description => "<p>The Kyoto collection features an Asian design influence reminiscent of temple architecture. &nbsp;Flared legs and stylish metal nail heads were inspired by oriental temple architecture and the simplicity of the Arts and Crafts movement.</p>\r\n" },
  { :name => "marbella", :title => "Marbella", :created_at => "2013-08-05 05:40:29", :updated_at => "2013-08-08 04:32:40", :description => "<p>Inspired by &nbsp;the kathy ireland Home&trade; Architectural Style Guide&trade; , Marbella showcases Serpentine curves that glide across the rectilinear form of this alluring collection. Marbella&#39;s simple yet sophisticated design features a russet finish complemented by matte black hardware.</p>\r\n" },
  { :name => "mission-pasadena", :title => "Mission Pasadena", :created_at => "2013-08-05 05:41:03", :updated_at => "2013-08-08 04:34:25", :description => "<p>Inspired by the kathy ireland Home&trade; Americana Style Guide&trade;, Mission Pasadena combines turn-of-the-century mission design with rustic simplicity. The glow of natural wood complemented by the mission-inspired finish and decorative structures make this collection a comfortable addition to any home.</p>\r\n" },
  { :name => "mount-view", :title => "Mount View", :created_at => "2013-08-05 05:41:40", :updated_at => "2013-08-08 04:35:06", :description => "<p>Inspired by the kathy ireland Home&trade; Americana Style Guide&trade;, Mount View offers contemporary conveniences with traditional design elements for today&#39;s home and executive office. Holding true to traditional American beauty, this furniture collection boasts richly grained hardwood with cherry veneers and book matched panels. Incredible durability, style and adaptable configurations combine to form a timeless collection.</p>\r\n" },
  { :name => "point-reyes", :title => "Point Reyes", :created_at => "2013-08-05 05:42:08", :updated_at => "2013-08-08 04:35:55", :description => "<p>The multidimensional toasted pecan finish of Point Reyes is accented by solid cast metal hardware and decorative metal corner appliqu&eacute;s. This handsome collection is marked by bold hardware and a warm highlighted finish. Point Reyes is a perfect blend of simplicity and functionality.</p>\r\n" },
  { :name => "portland-loft", :title => "Portland Loft", :created_at => "2013-08-05 05:42:35", :updated_at => "2013-08-08 04:36:21", :description => "<p>Inspired by the kathy ireland Home&trade; Americana Style Guide&trade;, Portland Loft is crafted with Elm hardwood solids, antique brass hardware and boasts a vibrant clove finish. Portland Loft combines functionality and style.</p>\r\n" },
  { :name => "san-ramon", :title => "San Ramon", :created_at => "2013-08-05 05:43:01", :updated_at => "2013-08-08 04:36:45", :description => "<p>The San Ramon collection offers sleek contemporary design with functional features. &nbsp;Crafted of acacia hardwood and veneers, it showcases a golden auburn finish that pairs seamlessly with matching wicker baskets. Large open shelves accommodate electronics or display items, while the optional wicker baskets organize and conceal your remote controls, DVDs or other entertainment accessories.</p>\r\n" },
  { :name => "southampton", :title => "Southampton", :created_at => "2013-08-05 05:43:27", :updated_at => "2013-08-08 04:37:17", :description => "<p>Inspired by the kathy ireland Home&trade; Americana Style Guide&trade;, Southampton is a charming and comfortable home office collection. Southampton is constructed with hardwood solids, and embodies the warmth of a sun filled cottage with a slightly distressed, painted finish and light maple tops on white or oak tops on black. Most pieces are available in both onyx black and oyster white finishes.</p>\r\n" },
  { :name => "tribeca-loft", :title => "Tribeca Loft", :created_at => "2013-08-05 05:43:55", :updated_at => "2013-08-08 04:37:43", :description => "<p>Inspired by &nbsp;the kathy ireland Home&trade; Architectural Style Guide&trade; , Tribeca Loft is a lifestyle design consistent with urban furniture trends. &nbsp;The functional features of Tribeca Loft combined with its soft modern style make this collection a true design solution for living. &nbsp;Tribeca loft is available in eggshell white, burnt umber cherry or midnight smoke black with hand-rubbed edges. &nbsp;Pewter colored hardware completes Tribeca Loft&rsquo;s timeless impression.</p>\r\n" },
  { :name => "waterfall", :title => "Waterfall", :created_at => "2013-08-05 05:44:24", :updated_at => "2013-08-08 04:38:11", :description => "<p>Waterfall is a timeless Martin Home Furnishings office furniture collection that is crafted with solids and oak veneers. Finger-pull handles on drawers and cupboards are just a few of the details featured in this collection. The multiple-step hand rubbed lacquer finish, well-defined bull-nose solid oak moldings and drawer fronts make Waterfall an excellent investment.</p>\r\n" },
  { :name => "worx", :title => "WorX", :created_at => "2013-08-05 05:44:44", :updated_at => "2013-08-08 04:38:48", :description => "<p>Inspired by the kathy ireland Home&trade; Architectural Style Guide&trade;, WorX exudes strength and balance with its linear foundation. This soft modern collection meets today&#39;s home office needs with thoughtful technology integration; wire management holes, electronics charging shelf and a flip down keyboard drawer. Stylish and practical, WorX is available in an Onyx Black finish.</p>\r\n" }
], :without_protection => true )



CollectionStyle.create([
  { :created_at => "2013-08-05 05:47:49", :updated_at => "2013-08-05 05:47:49", :collection_id => 2, :style_id => 1 },
  { :created_at => "2013-08-05 05:47:49", :updated_at => "2013-08-05 05:47:49", :collection_id => 3, :style_id => 1 },
  { :created_at => "2013-08-05 05:47:49", :updated_at => "2013-08-05 05:47:49", :collection_id => 13, :style_id => 1 },
  { :created_at => "2013-08-05 05:47:50", :updated_at => "2013-08-05 05:47:50", :collection_id => 18, :style_id => 1 },
  { :created_at => "2013-08-05 05:47:50", :updated_at => "2013-08-05 05:47:50", :collection_id => 19, :style_id => 1 },
  { :created_at => "2013-08-05 05:47:50", :updated_at => "2013-08-05 05:47:50", :collection_id => 21, :style_id => 1 },
  { :created_at => "2013-08-05 05:47:50", :updated_at => "2013-08-05 05:47:50", :collection_id => 23, :style_id => 1 },
  { :created_at => "2013-08-05 05:48:23", :updated_at => "2013-08-05 05:48:23", :collection_id => 4, :style_id => 2 },
  { :created_at => "2013-08-05 05:48:23", :updated_at => "2013-08-05 05:48:23", :collection_id => 5, :style_id => 2 },
  { :created_at => "2013-08-05 05:48:23", :updated_at => "2013-08-05 05:48:23", :collection_id => 7, :style_id => 2 },
  { :created_at => "2013-08-05 05:48:23", :updated_at => "2013-08-05 05:48:23", :collection_id => 8, :style_id => 2 },
  { :created_at => "2013-08-05 05:48:23", :updated_at => "2013-08-05 05:48:23", :collection_id => 10, :style_id => 2 },
  { :created_at => "2013-08-05 05:48:23", :updated_at => "2013-08-05 05:48:23", :collection_id => 12, :style_id => 2 },
  { :created_at => "2013-08-05 05:48:23", :updated_at => "2013-08-05 05:48:23", :collection_id => 14, :style_id => 2 },
  { :created_at => "2013-08-05 05:48:23", :updated_at => "2013-08-05 05:48:23", :collection_id => 15, :style_id => 2 },
  { :created_at => "2013-08-05 05:48:23", :updated_at => "2013-08-05 05:48:23", :collection_id => 24, :style_id => 2 },
  { :created_at => "2013-08-05 05:49:02", :updated_at => "2013-08-05 05:49:02", :collection_id => 4, :style_id => 3 },
  { :created_at => "2013-08-05 05:49:02", :updated_at => "2013-08-05 05:49:02", :collection_id => 6, :style_id => 3 },
  { :created_at => "2013-08-05 05:49:02", :updated_at => "2013-08-05 05:49:02", :collection_id => 7, :style_id => 3 },
  { :created_at => "2013-08-05 05:49:02", :updated_at => "2013-08-05 05:49:02", :collection_id => 8, :style_id => 3 },
  { :created_at => "2013-08-05 05:49:02", :updated_at => "2013-08-05 05:49:02", :collection_id => 9, :style_id => 3 },
  { :created_at => "2013-08-05 05:49:02", :updated_at => "2013-08-05 05:49:02", :collection_id => 11, :style_id => 3 },
  { :created_at => "2013-08-05 05:49:02", :updated_at => "2013-08-05 05:49:02", :collection_id => 12, :style_id => 3 },
  { :created_at => "2013-08-05 05:49:02", :updated_at => "2013-08-05 05:49:02", :collection_id => 14, :style_id => 3 },
  { :created_at => "2013-08-05 05:49:02", :updated_at => "2013-08-05 05:49:02", :collection_id => 16, :style_id => 3 },
  { :created_at => "2013-08-05 05:49:02", :updated_at => "2013-08-05 05:49:02", :collection_id => 17, :style_id => 3 },
  { :created_at => "2013-08-05 05:49:02", :updated_at => "2013-08-05 05:49:02", :collection_id => 24, :style_id => 3 },
  { :created_at => "2013-08-05 05:49:02", :updated_at => "2013-08-05 05:49:02", :collection_id => 25, :style_id => 3 },
  { :created_at => "2013-08-05 05:49:02", :updated_at => "2013-08-05 05:49:02", :collection_id => 26, :style_id => 3 },
  { :created_at => "2013-08-05 05:49:31", :updated_at => "2013-08-05 05:49:31", :collection_id => 3, :style_id => 4 },
  { :created_at => "2013-08-05 05:49:31", :updated_at => "2013-08-05 05:49:31", :collection_id => 18, :style_id => 4 },
  { :created_at => "2013-08-05 05:49:54", :updated_at => "2013-08-05 05:49:54", :collection_id => 1, :style_id => 5 },
  { :created_at => "2013-08-05 05:49:54", :updated_at => "2013-08-05 05:49:54", :collection_id => 13, :style_id => 5 },
  { :created_at => "2013-08-05 05:49:54", :updated_at => "2013-08-05 05:49:54", :collection_id => 19, :style_id => 5 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 1, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 2, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 3, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 4, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 5, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 6, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 7, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 8, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 9, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 10, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 11, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 12, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 13, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 14, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 15, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 16, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 17, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 18, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 19, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 20, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 21, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 22, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 23, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 24, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 25, :style_id => 6 },
  { :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:50:37", :collection_id => 26, :style_id => 6 }
], :without_protection => true )



Compilation.create([
  { :name => "desk-and-return", :title => "Desk and Return", :skin_id => 3, :collection_id => 1, :created_at => "2013-08-07 03:21:33", :updated_at => "2013-08-07 03:21:33", :active => true, :finish_id => 20, :include_finish_name => false },
  { :name => "u-shaped-desk", :title => "U-Shaped Desk", :skin_id => 3, :collection_id => 1, :created_at => "2013-08-07 19:23:41", :updated_at => "2013-08-07 19:23:41", :active => true, :finish_id => 20, :include_finish_name => false },
  { :name => "desk-and-return", :title => "Desk and Return", :skin_id => 3, :collection_id => 1, :created_at => "2013-08-07 19:25:11", :updated_at => "2013-08-07 19:25:11", :active => true, :finish_id => 20, :include_finish_name => false }
], :without_protection => true )



Component.create([
  { :name => "bookcases", :title => "Bookcases", :created_at => "2013-08-05 05:19:11", :updated_at => "2013-08-05 05:19:11", :category_id => 4, :parent_id => 0 },
  { :name => "charge-connect", :title => "Charge & Connect", :created_at => "2013-08-05 05:13:11", :updated_at => "2013-08-05 05:13:11", :category_id => 1, :parent_id => 0 },
  { :name => "coffee-tables", :title => "Coffee Tables", :created_at => "2013-08-05 05:14:25", :updated_at => "2013-08-05 05:14:25", :category_id => 3, :parent_id => 3 },
  { :name => "computer-carts", :title => "Computer Carts", :created_at => "2013-08-05 05:20:48", :updated_at => "2013-08-05 05:20:48", :category_id => 4, :parent_id => 17 },
  { :name => "conference-tables", :title => "Conference Tables", :created_at => "2013-08-05 05:19:37", :updated_at => "2013-08-05 05:19:37", :category_id => 4, :parent_id => 0 },
  { :name => "consoles", :title => "Consoles", :created_at => "2013-08-05 05:20:04", :updated_at => "2013-08-05 05:20:04", :category_id => 4, :parent_id => 0 },
  { :name => "corner-tv-stands", :title => "Corner TV Stands", :created_at => "2013-08-05 05:16:31", :updated_at => "2013-08-05 05:16:31", :category_id => 2, :parent_id => 7 },
  { :name => "credenzas", :title => "Credenzas", :created_at => "2013-08-05 05:21:11", :updated_at => "2013-08-05 05:21:11", :category_id => 4, :parent_id => 17 },
  { :name => "desks", :title => "Desks", :created_at => "2013-08-05 05:20:22", :updated_at => "2013-08-05 05:20:22", :category_id => 4, :parent_id => 0 },
  { :name => "double-pedestal-desks", :title => "Double Pedestal Desks", :created_at => "2013-08-05 05:21:33", :updated_at => "2013-08-05 05:21:33", :category_id => 4, :parent_id => 17 },
  { :name => "ewas-tv-consoles", :title => "EWAS TV Consoles", :created_at => "2013-08-05 05:16:48", :updated_at => "2013-08-05 05:16:48", :category_id => 2, :parent_id => 7 },
  { :name => "end-tables", :title => "End Tables", :created_at => "2013-08-05 05:14:04", :updated_at => "2013-08-05 05:14:04", :category_id => 3, :parent_id => 3 },
  { :name => "entertainment-walls", :title => "Entertainment Walls", :created_at => "2013-08-05 05:13:26", :updated_at => "2013-08-05 05:13:26", :category_id => 2, :parent_id => 0 },
  { :name => "filing-cabinets", :title => "Filing Cabinets", :created_at => "2013-08-05 05:23:13", :updated_at => "2013-08-05 05:23:13", :category_id => 4, :parent_id => 0 },
  { :name => "hutches", :title => "Hutches", :created_at => "2013-08-05 05:25:39", :updated_at => "2013-08-05 05:25:39", :category_id => 4, :parent_id => 0 },
  { :name => "l-shaped-desks", :title => "L-Shaped Desks", :created_at => "2013-08-05 05:21:49", :updated_at => "2013-08-05 05:21:49", :category_id => 4, :parent_id => 17 },
  { :name => "lateral-files", :title => "Lateral Files", :created_at => "2013-08-05 05:23:39", :updated_at => "2013-08-05 05:23:39", :category_id => 4, :parent_id => 25 },
  { :name => "modular-office", :title => "Modular Office", :created_at => "2013-08-05 05:25:57", :updated_at => "2013-08-05 05:25:57", :category_id => 4, :parent_id => 0 },
  { :name => "multifunction-files", :title => "Multifunction Files", :created_at => "2013-08-05 05:24:01", :updated_at => "2013-08-05 05:24:01", :category_id => 4, :parent_id => 25 },
  { :name => "occasional-tables", :title => "Occasional Tables", :created_at => "2013-08-05 05:13:40", :updated_at => "2013-08-05 05:13:40", :category_id => 2, :parent_id => 0 },
  { :name => "piers-bookcases", :title => "Piers/Bookcases", :created_at => "2013-08-05 05:14:41", :updated_at => "2013-08-05 05:14:41", :category_id => 2, :parent_id => 0 },
  { :name => "rolling-files", :title => "Rolling Files", :created_at => "2013-08-05 05:24:23", :updated_at => "2013-08-05 05:24:23", :category_id => 4, :parent_id => 25 },
  { :name => "single-pedestal-desks", :title => "Single Pedestal Desks", :created_at => "2013-08-05 05:22:10", :updated_at => "2013-08-05 05:22:10", :category_id => 4, :parent_id => 17 },
  { :name => "tv-consoles", :title => "TV Consoles", :created_at => "2013-08-05 05:15:27", :updated_at => "2013-08-05 05:15:27", :category_id => 2, :parent_id => 0 },
  { :name => "tv-consoles-50-59", :title => "TV Consoles 50\" - 59\"", :created_at => "2013-08-05 05:17:30", :updated_at => "2013-08-05 05:17:30", :category_id => 2, :parent_id => 7 },
  { :name => "tv-consoles-60-69", :title => "TV Consoles 60\" - 69\"", :created_at => "2013-08-05 05:18:03", :updated_at => "2013-08-05 05:18:03", :category_id => 2, :parent_id => 7 },
  { :name => "tv-consoles-over-70", :title => "TV Consoles Over 70\"", :created_at => "2013-08-05 05:18:35", :updated_at => "2013-08-05 05:18:35", :category_id => 2, :parent_id => 7 },
  { :name => "tv-consoles-under-50", :title => "TV Consoles Under 50\"", :created_at => "2013-08-05 05:17:09", :updated_at => "2013-08-05 05:17:09", :category_id => 2, :parent_id => 7 },
  { :name => "u-shaped-desks", :title => "U-Shaped Desks", :created_at => "2013-08-05 05:22:29", :updated_at => "2013-08-05 05:22:29", :category_id => 4, :parent_id => 17 },
  { :name => "vertical-files", :title => "Vertical Files", :created_at => "2013-08-05 05:25:07", :updated_at => "2013-08-05 05:25:07", :category_id => 4, :parent_id => 25 },
  { :name => "writing-desks", :title => "Writing Desks", :created_at => "2013-08-05 05:22:52", :updated_at => "2013-08-05 05:22:52", :category_id => 4, :parent_id => 17 }
], :without_protection => true )



Dimension.create([
  { :created_at => "2013-08-06 22:13:25", :updated_at => "2013-08-06 22:13:25", :width => 36.0, :height => 30.0, :depth => 24.0, :product_id => 1, :name => "overall-dimensions", :title => "Overall Dimensions" },
  { :created_at => "2013-08-06 22:33:35", :updated_at => "2013-08-06 22:33:35", :width => 72.0, :height => 48.75, :depth => 14.75, :product_id => 2, :name => "overall-dimensions", :title => "Overall Dimensions" },
  { :created_at => "2013-08-06 22:38:00", :updated_at => "2013-08-06 22:38:00", :width => 48.0, :height => 30.0, :depth => 24.0, :product_id => 3, :name => "overall-dimensions", :title => "Overall Dimensions" },
  { :created_at => "2013-08-06 22:46:55", :updated_at => "2013-08-06 22:46:55", :width => 48.0, :height => 30.0, :depth => 24.0, :product_id => 4, :name => "overall-dimensions", :title => "Overall Dimensions" },
  { :created_at => "2013-08-07 00:28:42", :updated_at => "2013-08-07 00:28:42", :width => 72.0, :height => 30.0, :depth => 36.0, :product_id => 5, :name => "overall-dimensions", :title => "Overall Dimensions" },
  { :created_at => "2013-08-07 00:32:20", :updated_at => "2013-08-07 00:32:20", :width => 72.0, :height => 30.0, :depth => 24.0, :product_id => 6, :name => "overall-dimensions", :title => "Overall Dimensions" },
  { :created_at => "2013-08-07 00:37:25", :updated_at => "2013-08-07 00:37:25", :width => 48.0, :height => 30.0, :depth => 24.0, :product_id => 7, :name => "overall-dimensions", :title => "Overall Dimensions" },
  { :created_at => "2013-08-07 00:40:13", :updated_at => "2013-08-07 00:40:13", :width => 72.0, :height => 30.0, :depth => 36.0, :product_id => 8, :name => "overall-dimensions", :title => "Overall Dimensions" },
  { :created_at => "2013-08-07 00:45:18", :updated_at => "2013-08-07 00:45:18", :width => 72.0, :height => 30.0, :depth => 24.0, :product_id => 9, :name => "overall-dimensions", :title => "Overall Dimensions" },
  { :created_at => "2013-08-07 00:48:48", :updated_at => "2013-08-07 00:48:48", :width => 72.0, :height => 30.0, :depth => 36.0, :product_id => 10, :name => "overall-dimensions", :title => "Overall Dimensions" },
  { :created_at => "2013-08-07 00:52:43", :updated_at => "2013-08-07 00:52:43", :width => 36.0, :height => 78.0, :depth => 15.0, :product_id => 11, :name => "overall-dimensions", :title => "Overall Dimensions" },
  { :created_at => "2013-08-07 01:00:14", :updated_at => "2013-08-07 01:00:14", :width => 46.0, :height => 78.0, :depth => 15.0, :product_id => 12, :name => "overall-dimensions", :title => "Overall Dimensions" },
  { :created_at => "2013-08-08 15:37:12", :updated_at => "2013-08-08 15:37:12", :width => 18.0, :height => 24.0, :depth => 23.75, :product_id => 13, :name => "overall-dimensions", :title => "Overall Dimensions" },
  { :created_at => "2013-08-08 15:50:29", :updated_at => "2013-08-08 15:50:29", :width => 23.75, :height => 24.0, :depth => 23.75, :product_id => 14, :name => "overall-dimensions", :title => "Overall Dimensions" }
], :without_protection => true )



Figure.create([
  { :caption => "", :created_at => "2013-08-05 05:10:20", :updated_at => "2013-08-05 05:10:20", :page_id => nil, :link => "#", :carousel_id => 1 },
  { :caption => "", :created_at => "2013-08-05 05:10:21", :updated_at => "2013-08-05 05:10:21", :page_id => nil, :link => "#", :carousel_id => 1 },
  { :caption => "", :created_at => "2013-08-05 05:10:21", :updated_at => "2013-08-05 05:10:21", :page_id => nil, :link => "#", :carousel_id => 1 },
  { :caption => "", :created_at => "2013-08-05 05:10:21", :updated_at => "2013-08-05 05:10:21", :page_id => nil, :link => "#", :carousel_id => 1 },
  { :caption => "", :created_at => "2013-08-05 05:10:21", :updated_at => "2013-08-05 05:10:21", :page_id => nil, :link => "#", :carousel_id => 1 },
  { :caption => "", :created_at => "2013-08-05 05:10:21", :updated_at => "2013-08-05 05:10:21", :page_id => 1, :link => "#", :carousel_id => nil },
  { :caption => "", :created_at => "2013-08-05 05:10:21", :updated_at => "2013-08-05 05:10:21", :page_id => 1, :link => "#", :carousel_id => nil },
  { :caption => "", :created_at => "2013-08-05 05:10:21", :updated_at => "2013-08-05 05:10:21", :page_id => 1, :link => "#", :carousel_id => nil }
], :without_protection => true )



Finish.create([
  { :name => "bourbon", :title => "Bourbon", :created_at => "2013-08-05 18:21:05", :updated_at => "2013-08-05 18:21:05" },
  { :name => "bright-white", :title => "Bright White", :created_at => "2013-08-05 18:22:25", :updated_at => "2013-08-05 18:22:25" },
  { :name => "burnish", :title => "Burnish", :created_at => "2013-08-05 18:23:09", :updated_at => "2013-08-05 18:23:09" },
  { :name => "burnt-umber-cherry", :title => "Burnt Umber Cherry", :created_at => "2013-08-05 18:23:42", :updated_at => "2013-08-05 18:23:42" },
  { :name => "carmel", :title => "Carmel", :created_at => "2013-08-05 18:24:04", :updated_at => "2013-08-05 18:24:04" },
  { :name => "chestnut", :title => "Chestnut", :created_at => "2013-08-05 18:24:33", :updated_at => "2013-08-05 18:24:33" },
  { :name => "clove", :title => "Clove", :created_at => "2013-08-05 18:24:49", :updated_at => "2013-08-05 18:24:49" },
  { :name => "cobblestone-cherry", :title => "Cobblestone Cherry", :created_at => "2013-08-05 18:25:08", :updated_at => "2013-08-05 18:25:08" },
  { :name => "dark-chocolate", :title => "Dark Chocolate", :created_at => "2013-08-05 18:25:24", :updated_at => "2013-08-05 18:25:24" },
  { :name => "deep-java", :title => "Deep Java", :created_at => "2013-08-05 18:25:42", :updated_at => "2013-08-05 18:25:42" },
  { :name => "eggshell-white", :title => "Eggshell White", :created_at => "2013-08-05 18:26:04", :updated_at => "2013-08-05 18:26:04" },
  { :name => "espresso", :title => "Espresso", :created_at => "2013-08-05 18:26:18", :updated_at => "2013-08-05 18:26:18" },
  { :name => "golden-auburn", :title => "Golden Auburn", :created_at => "2013-08-05 18:26:37", :updated_at => "2013-08-05 18:26:37" },
  { :name => "maple", :title => "Maple", :created_at => "2013-08-05 18:26:59", :updated_at => "2013-08-05 18:26:59" },
  { :name => "medium-oak", :title => "Medium Oak", :created_at => "2013-08-05 18:27:18", :updated_at => "2013-08-05 18:27:18" },
  { :name => "midnight-smoke-black", :title => "Midnight Smoke Black", :created_at => "2013-08-05 18:27:42", :updated_at => "2013-08-05 18:27:42" },
  { :name => "mission", :title => "Mission", :created_at => "2013-08-05 18:28:12", :updated_at => "2013-08-05 18:28:12" },
  { :name => "onyx-black", :title => "Onyx Black", :created_at => "2013-08-05 18:28:32", :updated_at => "2013-08-05 18:28:32" },
  { :name => "oyster-white", :title => "Oyster White", :created_at => "2013-08-05 18:29:00", :updated_at => "2013-08-05 18:29:00" },
  { :name => "port", :title => "Port", :created_at => "2013-08-05 18:29:18", :updated_at => "2013-08-05 18:29:18" },
  { :name => "pure-white", :title => "Pure White", :created_at => "2013-08-05 18:29:38", :updated_at => "2013-08-05 18:29:38" },
  { :name => "rich-cherry", :title => "Rich Cherry", :created_at => "2013-08-05 18:29:57", :updated_at => "2013-08-05 18:29:57" },
  { :name => "russet", :title => "Russet", :created_at => "2013-08-05 18:30:12", :updated_at => "2013-08-05 18:30:12" },
  { :name => "toasted-peacan", :title => "Toasted Peacan", :created_at => "2013-08-05 18:30:33", :updated_at => "2013-08-05 18:30:33" },
  { :name => "vibrant-cherry", :title => "Vibrant Cherry", :created_at => "2013-08-05 18:30:52", :updated_at => "2013-08-05 18:30:52" },
  { :name => "warm-fruitwood", :title => "Warm Fruitwood", :created_at => "2013-08-05 18:31:11", :updated_at => "2013-08-05 18:31:11" },
  { :name => "wheat", :title => "Wheat", :created_at => "2013-08-05 18:31:30", :updated_at => "2013-08-05 18:31:30" }
], :without_protection => true )



Image.create([
  { :imageable_id => 1, :imageable_type => "Figure", :created_at => "2013-08-05 05:10:20", :updated_at => "2013-08-05 05:10:20", :asset => "v1375679359/ah1kqk0nr93evvzwfayh.jpg" },
  { :imageable_id => 2, :imageable_type => "Figure", :created_at => "2013-08-05 05:10:21", :updated_at => "2013-08-05 05:10:21", :asset => "v1375679379/wy64ogjubv0bq7alegi2.jpg" },
  { :imageable_id => 3, :imageable_type => "Figure", :created_at => "2013-08-05 05:10:21", :updated_at => "2013-08-05 05:10:21", :asset => "v1375679385/q0x2ct6dmxt7yg77i3zs.jpg" },
  { :imageable_id => 4, :imageable_type => "Figure", :created_at => "2013-08-05 05:10:21", :updated_at => "2013-08-05 05:10:21", :asset => "v1375679390/r0ibty3nwlurehehfutg.jpg" },
  { :imageable_id => 5, :imageable_type => "Figure", :created_at => "2013-08-05 05:10:21", :updated_at => "2013-08-05 05:10:21", :asset => "v1375679397/hfx2i6hkuly9qlaweliu.jpg" },
  { :imageable_id => 6, :imageable_type => "Figure", :created_at => "2013-08-05 05:10:21", :updated_at => "2013-08-05 05:10:21", :asset => "v1375679403/sddrya447atsi5vwhzin.jpg" },
  { :imageable_id => 7, :imageable_type => "Figure", :created_at => "2013-08-05 05:10:21", :updated_at => "2013-08-05 05:10:21", :asset => "v1375679411/bmjhmvyiupqptfzctofu.jpg" },
  { :imageable_id => 8, :imageable_type => "Figure", :created_at => "2013-08-05 05:10:21", :updated_at => "2013-08-05 05:10:21", :asset => "v1375679416/iqjhg2yyahh6eylcl12w.jpg" },
  { :imageable_id => 1, :imageable_type => "Brand", :created_at => "2013-08-05 05:51:56", :updated_at => "2013-08-05 05:51:56", :asset => "v1375681910/bzmveb6nxv58zuptzxhb.jpg" },
  { :imageable_id => 1, :imageable_type => "Finish", :created_at => "2013-08-05 18:21:25", :updated_at => "2013-08-05 18:21:25", :asset => "v1375726861/pe3m0cepfszd1cjfvtsd.jpg" },
  { :imageable_id => 2, :imageable_type => "Finish", :created_at => "2013-08-05 18:22:25", :updated_at => "2013-08-05 18:22:25", :asset => "v1375726943/h3ejt9r9mowwsytmacsl.jpg" },
  { :imageable_id => 3, :imageable_type => "Finish", :created_at => "2013-08-05 18:23:09", :updated_at => "2013-08-05 18:23:09", :asset => "v1375726983/njxaf4oa8iyeghcipxoa.jpg" },
  { :imageable_id => 4, :imageable_type => "Finish", :created_at => "2013-08-05 18:23:42", :updated_at => "2013-08-05 18:23:42", :asset => "v1375727020/tcjeumiwnmck6q6lfodk.jpg" },
  { :imageable_id => 5, :imageable_type => "Finish", :created_at => "2013-08-05 18:24:04", :updated_at => "2013-08-05 18:24:04", :asset => "v1375727042/xsjibpw6ih6oqnos2ldh.jpg" },
  { :imageable_id => 6, :imageable_type => "Finish", :created_at => "2013-08-05 18:24:33", :updated_at => "2013-08-05 18:24:33", :asset => "v1375727070/nqtqqmrgleuye3ktfqlw.jpg" },
  { :imageable_id => 7, :imageable_type => "Finish", :created_at => "2013-08-05 18:24:49", :updated_at => "2013-08-05 18:24:49", :asset => "v1375727086/mjk62siwgbvkoiw2w2ym.jpg" },
  { :imageable_id => 8, :imageable_type => "Finish", :created_at => "2013-08-05 18:25:08", :updated_at => "2013-08-05 18:25:08", :asset => "v1375727106/upydo89q6pcjpu8vpqf3.jpg" },
  { :imageable_id => 9, :imageable_type => "Finish", :created_at => "2013-08-05 18:25:24", :updated_at => "2013-08-05 18:25:24", :asset => "v1375727120/pjedo5g8qgp09j1gwqt0.jpg" },
  { :imageable_id => 10, :imageable_type => "Finish", :created_at => "2013-08-05 18:25:42", :updated_at => "2013-08-05 18:25:42", :asset => "v1375727138/ywsnbdkzjz8ngof2lvk5.jpg" },
  { :imageable_id => 11, :imageable_type => "Finish", :created_at => "2013-08-05 18:26:04", :updated_at => "2013-08-05 18:26:04", :asset => "v1375727159/owybb0xaxdlhgfyvwtwx.jpg" },
  { :imageable_id => 12, :imageable_type => "Finish", :created_at => "2013-08-05 18:26:18", :updated_at => "2013-08-05 18:26:18", :asset => "v1375727175/j2nftzpdltqctpiagxum.jpg" },
  { :imageable_id => 13, :imageable_type => "Finish", :created_at => "2013-08-05 18:26:37", :updated_at => "2013-08-05 18:26:37", :asset => "v1375727193/kznazy6bq1tksab0cydg.jpg" },
  { :imageable_id => 14, :imageable_type => "Finish", :created_at => "2013-08-05 18:26:59", :updated_at => "2013-08-05 18:26:59", :asset => "v1375727212/t2k5zzjsa7lspl2fm5ky.jpg" },
  { :imageable_id => 15, :imageable_type => "Finish", :created_at => "2013-08-05 18:27:18", :updated_at => "2013-08-05 18:27:18", :asset => "v1375727235/q9f4jc2whi7aip1czka0.jpg" },
  { :imageable_id => 16, :imageable_type => "Finish", :created_at => "2013-08-05 18:27:42", :updated_at => "2013-08-05 18:27:42", :asset => "v1375727255/tfkdw2fk6cwsmannwseo.jpg" },
  { :imageable_id => 17, :imageable_type => "Finish", :created_at => "2013-08-05 18:28:12", :updated_at => "2013-08-05 18:28:12", :asset => "v1375727285/hqz9amfd90g0ogynjfce.jpg" },
  { :imageable_id => 18, :imageable_type => "Finish", :created_at => "2013-08-05 18:28:32", :updated_at => "2013-08-05 18:28:32", :asset => "v1375727309/qygil5mnlvoakiviwy8e.jpg" },
  { :imageable_id => 19, :imageable_type => "Finish", :created_at => "2013-08-05 18:29:00", :updated_at => "2013-08-05 18:29:00", :asset => "v1375727335/vimediew592lve81lywl.jpg" },
  { :imageable_id => 20, :imageable_type => "Finish", :created_at => "2013-08-05 18:29:18", :updated_at => "2013-08-05 18:29:18", :asset => "v1375727354/m7e9kwh503mu1qnr3tpj.jpg" },
  { :imageable_id => 21, :imageable_type => "Finish", :created_at => "2013-08-05 18:29:38", :updated_at => "2013-08-05 18:29:38", :asset => "v1375727376/gv4vyrtkfk8l1bwrkbpj.jpg" },
  { :imageable_id => 22, :imageable_type => "Finish", :created_at => "2013-08-05 18:29:57", :updated_at => "2013-08-05 18:29:57", :asset => "v1375727395/if70xh2lhcxmq8e7ikzp.jpg" },
  { :imageable_id => 23, :imageable_type => "Finish", :created_at => "2013-08-05 18:30:12", :updated_at => "2013-08-05 18:30:12", :asset => "v1375727409/mlihd7iz84hqlbfimadk.jpg" },
  { :imageable_id => 24, :imageable_type => "Finish", :created_at => "2013-08-05 18:30:33", :updated_at => "2013-08-05 18:30:33", :asset => "v1375727430/fbac4afq6d7oaqknqzve.jpg" },
  { :imageable_id => 25, :imageable_type => "Finish", :created_at => "2013-08-05 18:30:52", :updated_at => "2013-08-05 18:30:52", :asset => "v1375727451/a6kmu47fyu6qvzveuq5x.jpg" },
  { :imageable_id => 26, :imageable_type => "Finish", :created_at => "2013-08-05 18:31:11", :updated_at => "2013-08-05 18:31:11", :asset => "v1375727465/tnl6v42ghrwopnv7vom3.jpg" },
  { :imageable_id => 27, :imageable_type => "Finish", :created_at => "2013-08-05 18:31:30", :updated_at => "2013-08-05 18:31:30", :asset => "v1375727485/wuds25az57j2r2adszi3.jpg" },
  { :imageable_id => 1, :imageable_type => "Sku", :created_at => "2013-08-06 22:13:25", :updated_at => "2013-08-06 22:13:25", :asset => "v1375827160/hcitzkzz0v9ccdaajigw.jpg" },
  { :imageable_id => 1, :imageable_type => "Sku", :created_at => "2013-08-06 22:13:25", :updated_at => "2013-08-06 22:13:25", :asset => "v1375827187/ehimolgscmkr5sspvihz.jpg" },
  { :imageable_id => 1, :imageable_type => "Sku", :created_at => "2013-08-06 22:13:25", :updated_at => "2013-08-06 22:13:25", :asset => "v1375827190/vscvalaygdy3hfl2agce.jpg" },
  { :imageable_id => 1, :imageable_type => "Sku", :created_at => "2013-08-06 22:13:25", :updated_at => "2013-08-06 22:13:25", :asset => "v1375827193/zqgiuh4cptzxqgk0kaku.jpg" },
  { :imageable_id => 1, :imageable_type => "Sku", :created_at => "2013-08-06 22:13:25", :updated_at => "2013-08-06 22:13:25", :asset => "v1375827197/kotu4iiqq41uaaktuglh.jpg" },
  { :imageable_id => 2, :imageable_type => "Sku", :created_at => "2013-08-06 22:33:35", :updated_at => "2013-08-06 22:33:35", :asset => "v1375828387/cx1q8hjmvcz0fmuup0dj.jpg" },
  { :imageable_id => 2, :imageable_type => "Sku", :created_at => "2013-08-06 22:33:35", :updated_at => "2013-08-06 22:33:35", :asset => "v1375828391/ll6utgjrtiopjzfu6nqb.jpg" },
  { :imageable_id => 2, :imageable_type => "Sku", :created_at => "2013-08-06 22:33:35", :updated_at => "2013-08-06 22:33:35", :asset => "v1375828394/hsmjeaogqw0cu9zp4ah6.jpg" },
  { :imageable_id => 2, :imageable_type => "Sku", :created_at => "2013-08-06 22:33:35", :updated_at => "2013-08-06 22:33:35", :asset => "v1375828398/xj7edx5augizlxgstbeu.jpg" },
  { :imageable_id => 2, :imageable_type => "Sku", :created_at => "2013-08-06 22:33:35", :updated_at => "2013-08-06 22:33:35", :asset => "v1375828400/t3hbw0hwzywfzv9bhdob.jpg" },
  { :imageable_id => 3, :imageable_type => "Sku", :created_at => "2013-08-06 22:38:00", :updated_at => "2013-08-06 22:38:00", :asset => "v1375828679/ghauxrnakmnsv4xbcdep.jpg" },
  { :imageable_id => 4, :imageable_type => "Sku", :created_at => "2013-08-06 22:46:55", :updated_at => "2013-08-06 22:46:55", :asset => "v1375829209/u2oc8ljurqt5sn9l6lln.jpg" },
  { :imageable_id => 5, :imageable_type => "Sku", :created_at => "2013-08-07 00:28:42", :updated_at => "2013-08-07 00:28:42", :asset => "v1375835311/nvccy8atk8pmfbataqke.jpg" },
  { :imageable_id => 6, :imageable_type => "Dimension", :created_at => "2013-08-07 00:32:20", :updated_at => "2013-08-07 00:32:20", :asset => "v1375835492/awx6u4ptl9cypa0u2lwf.jpg" },
  { :imageable_id => 6, :imageable_type => "Sku", :created_at => "2013-08-07 00:32:20", :updated_at => "2013-08-07 00:32:20", :asset => "v1375835538/ojdq1i6tb5xmqljoqqdn.jpg" },
  { :imageable_id => 7, :imageable_type => "Sku", :created_at => "2013-08-07 00:37:25", :updated_at => "2013-08-07 00:37:25", :asset => "v1375835837/v3gwijfpj83bilqvfqhc.jpg" },
  { :imageable_id => 8, :imageable_type => "Sku", :created_at => "2013-08-07 00:40:13", :updated_at => "2013-08-07 00:40:13", :asset => "v1375836009/xay5trzzc1hno4ixezkl.jpg" },
  { :imageable_id => 9, :imageable_type => "Sku", :created_at => "2013-08-07 00:45:18", :updated_at => "2013-08-07 00:45:18", :asset => "v1375836297/musadsta9qj8qwxq1uzy.jpg" },
  { :imageable_id => 9, :imageable_type => "Sku", :created_at => "2013-08-07 00:45:18", :updated_at => "2013-08-07 00:45:18", :asset => "v1375836300/yba2guhhprzqqotvnlym.jpg" },
  { :imageable_id => 9, :imageable_type => "Sku", :created_at => "2013-08-07 00:45:18", :updated_at => "2013-08-07 00:45:18", :asset => "v1375836303/kwqf3xejnqziu642wlh0.jpg" },
  { :imageable_id => 9, :imageable_type => "Sku", :created_at => "2013-08-07 00:45:18", :updated_at => "2013-08-07 00:45:18", :asset => "v1375836306/fpbomixzszg2wom4nfvn.jpg" },
  { :imageable_id => 9, :imageable_type => "Sku", :created_at => "2013-08-07 00:45:18", :updated_at => "2013-08-07 00:45:18", :asset => "v1375836308/d11w09tjljepz22n4i1f.jpg" },
  { :imageable_id => 10, :imageable_type => "Sku", :created_at => "2013-08-07 00:48:48", :updated_at => "2013-08-07 00:48:48", :asset => "v1375836501/aikjboox9xxxbs8alero.jpg" },
  { :imageable_id => 10, :imageable_type => "Sku", :created_at => "2013-08-07 00:48:49", :updated_at => "2013-08-07 00:48:49", :asset => "v1375836509/khlhmzp6c0akafgnhr1q.jpg" },
  { :imageable_id => 10, :imageable_type => "Sku", :created_at => "2013-08-07 00:48:49", :updated_at => "2013-08-07 00:48:49", :asset => "v1375836512/ibtsw9pcjn9rjgzcybzo.jpg" },
  { :imageable_id => 10, :imageable_type => "Sku", :created_at => "2013-08-07 00:48:49", :updated_at => "2013-08-07 00:48:49", :asset => "v1375836516/pmigzgdqz2irm5mqjgmv.jpg" },
  { :imageable_id => 10, :imageable_type => "Sku", :created_at => "2013-08-07 00:48:49", :updated_at => "2013-08-07 00:48:49", :asset => "v1375836519/bpqodil7lo7zhd7033bq.jpg" },
  { :imageable_id => 11, :imageable_type => "Sku", :created_at => "2013-08-07 00:52:43", :updated_at => "2013-08-07 00:52:43", :asset => "v1375836751/fwrnufa0awulwydydl4t.jpg" },
  { :imageable_id => 11, :imageable_type => "Sku", :created_at => "2013-08-07 00:52:43", :updated_at => "2013-08-07 00:52:43", :asset => "v1375836755/qe5lyhi9yngp5nxpz2y8.jpg" },
  { :imageable_id => 11, :imageable_type => "Sku", :created_at => "2013-08-07 00:52:43", :updated_at => "2013-08-07 00:52:43", :asset => "v1375836758/u6de22zkginube6w6gqk.jpg" },
  { :imageable_id => 12, :imageable_type => "Sku", :created_at => "2013-08-07 01:00:14", :updated_at => "2013-08-07 01:00:14", :asset => "v1375837200/ttzuqpj3j6a6khpcxnba.jpg" },
  { :imageable_id => 12, :imageable_type => "Sku", :created_at => "2013-08-07 01:00:14", :updated_at => "2013-08-07 01:00:14", :asset => "v1375837206/wyaoly1dzp0sdwqetmlv.jpg" },
  { :imageable_id => 12, :imageable_type => "Sku", :created_at => "2013-08-07 01:00:14", :updated_at => "2013-08-07 01:00:14", :asset => "v1375837209/bjer1ut4cydulsekcxnw.jpg" },
  { :imageable_id => 1, :imageable_type => "Compilation", :created_at => "2013-08-07 03:21:33", :updated_at => "2013-08-07 03:21:33", :asset => "v1375845660/atn25mbpt5sjqvqcrx2r.jpg" },
  { :imageable_id => 1, :imageable_type => "Compilation", :created_at => "2013-08-07 03:21:33", :updated_at => "2013-08-07 03:21:33", :asset => "v1375845663/txrc8vxncavw19cdswta.jpg" },
  { :imageable_id => 1, :imageable_type => "Compilation", :created_at => "2013-08-07 03:21:33", :updated_at => "2013-08-07 03:21:33", :asset => "v1375845667/lbdzirlgaerd9iio2dcl.jpg" },
  { :imageable_id => 1, :imageable_type => "Compilation", :created_at => "2013-08-07 03:21:33", :updated_at => "2013-08-07 03:21:33", :asset => "v1375845673/eyvu2vntnc1fb5lifuve.jpg" },
  { :imageable_id => 2, :imageable_type => "Compilation", :created_at => "2013-08-07 19:23:45", :updated_at => "2013-08-07 19:23:45", :asset => "v1375903388/wvaxbkyd9upj62culpr3.jpg" },
  { :imageable_id => 2, :imageable_type => "Compilation", :created_at => "2013-08-07 19:23:47", :updated_at => "2013-08-07 19:23:47", :asset => "v1375903392/xc3dfdetdmjo0veyy9jx.jpg" },
  { :imageable_id => 2, :imageable_type => "Compilation", :created_at => "2013-08-07 19:23:47", :updated_at => "2013-08-07 19:23:47", :asset => "v1375903395/ddc0ijpdbzzg5ie5y9kg.jpg" },
  { :imageable_id => 3, :imageable_type => "Compilation", :created_at => "2013-08-07 19:25:11", :updated_at => "2013-08-07 19:25:11", :asset => "v1375903466/rgfoeowxizjtxbw5sqg9.jpg" },
  { :imageable_id => 3, :imageable_type => "Compilation", :created_at => "2013-08-07 19:25:11", :updated_at => "2013-08-07 19:25:11", :asset => "v1375903470/sazdq8jss4cp3iiglmfe.jpg" },
  { :imageable_id => 3, :imageable_type => "Compilation", :created_at => "2013-08-07 19:25:11", :updated_at => "2013-08-07 19:25:11", :asset => "v1375903472/do7jtsi0sbudtei8rswb.jpg" },
  { :imageable_id => 3, :imageable_type => "Compilation", :created_at => "2013-08-07 19:25:11", :updated_at => "2013-08-07 19:25:11", :asset => "v1375903478/qdcwajndgjntuxecvc7g.jpg" },
  { :imageable_id => 13, :imageable_type => "Sku", :created_at => "2013-08-08 15:37:12", :updated_at => "2013-08-08 15:37:12", :asset => "v1375976079/jksobxl1yxem9tl74rsk.jpg" },
  { :imageable_id => 13, :imageable_type => "Sku", :created_at => "2013-08-08 15:37:12", :updated_at => "2013-08-08 15:37:12", :asset => "v1375976091/n3yi7revmmayxsqwo3ek.jpg" },
  { :imageable_id => 13, :imageable_type => "Sku", :created_at => "2013-08-08 15:37:12", :updated_at => "2013-08-08 15:37:12", :asset => "v1375976096/wycoeoy8fl0ms0h4gn05.jpg" },
  { :imageable_id => 14, :imageable_type => "Sku", :created_at => "2013-08-08 15:50:29", :updated_at => "2013-08-08 15:50:29", :asset => "v1375976968/ejkvzh7knmuoiteyd7dm.jpg" },
  { :imageable_id => 14, :imageable_type => "Sku", :created_at => "2013-08-08 15:50:29", :updated_at => "2013-08-08 15:50:29", :asset => "v1375976973/f9vwe9twpayps8jkfavb.jpg" },
  { :imageable_id => 14, :imageable_type => "Sku", :created_at => "2013-08-08 15:50:29", :updated_at => "2013-08-08 15:50:29", :asset => "v1375976978/tt7ufp9qbyidsfobljxi.jpg" },
  { :imageable_id => 14, :imageable_type => "Sku", :created_at => "2013-08-08 15:50:29", :updated_at => "2013-08-08 15:50:29", :asset => "v1375976984/vufm9px7yis70a1psqxf.jpg" }
], :without_protection => true )



Page.create([
  { :name => "home", :title => "Home", :content => "", :created_at => "2013-08-05 05:10:20", :updated_at => "2013-08-05 05:10:20", :skin_id => 1 }
], :without_protection => true )



Product.create([
  { :name => "two-drawer-lateral-file", :title => "Two Drawer Lateral File", :created_at => "2013-08-06 22:13:25", :updated_at => "2013-08-06 22:13:25", :collection_id => 1, :skin_id => 2, :video => "", :features => "<ul>\r\n\t<li>Two locking letter/legal file drawers</li>\r\n</ul>\r\n", :active => true, :shown => true, :include_finish_name => false },
  { :name => "hutch", :title => "Hutch", :created_at => "2013-08-06 22:33:35", :updated_at => "2013-08-06 22:33:35", :collection_id => 1, :skin_id => 2, :video => "", :features => "<ul>\r\n\t<li>One center glass shelf</li>\r\n\t<li>One glass shelf behind each wood door</li>\r\n\t<li>Center can light with 3 stage touch dimmer</li>\r\n</ul>\r\n", :active => true, :shown => true, :include_finish_name => false },
  { :name => "bridge", :title => "Bridge", :created_at => "2013-08-06 22:38:00", :updated_at => "2013-08-06 22:38:00", :collection_id => 1, :skin_id => 2, :video => "", :features => "<ul>\r\n\t<li>Drop down keyboard/pencil drawer</li>\r\n\t<li>Wire management grommet</li>\r\n</ul>\r\n", :active => true, :shown => false, :include_finish_name => false },
  { :name => "left-hand-facing-keyboard-return", :title => "Left Hand Facing Keyboard Return", :created_at => "2013-08-06 22:46:55", :updated_at => "2013-08-07 00:26:02", :collection_id => 1, :skin_id => 2, :video => "", :features => "<ul>\r\n\t<li>Drop down keyboard/pencil drawer</li>\r\n\t<li>Wire management grommet</li>\r\n\t<li>One pencil drawer</li>\r\n\t<li>One utility drawer with dividers</li>\r\n\t<li>One locking letter/legal file drawer</li>\r\n</ul>\r\n", :active => true, :shown => false, :include_finish_name => false },
  { :name => "desk-for-left-hand-facing-keyboard-return-or-bridge", :title => "Desk for Left Hand Facing Keyboard Return or Bridge", :created_at => "2013-08-07 00:28:42", :updated_at => "2013-08-07 00:28:42", :collection_id => 1, :skin_id => 2, :video => "", :features => "<ul>\r\n\t<li>Drop down keyboard/pencil drawer</li>\r\n\t<li>Wire management hole accommodates Charge &amp; Connect</li>\r\n\t<li>One pencil drawer</li>\r\n\t<li>One utility drawer with dividers</li>\r\n\t<li>One locking letter/legal file drawer</li>\r\n</ul>\r\n", :active => true, :shown => false, :include_finish_name => false },
  { :name => "right-hand-facing-credenza", :title => "Right Hand Facing Credenza", :created_at => "2013-08-07 00:32:20", :updated_at => "2013-08-07 00:32:50", :collection_id => 1, :skin_id => 2, :video => "", :features => "<ul>\r\n\t<li>Drop down keyboard/pencil drawer</li>\r\n\t<li>One utility drawer with dividers Wire management grommet</li>\r\n\t<li>One locking letter/legal file drawer</li>\r\n</ul>\r\n", :active => true, :shown => false, :include_finish_name => false },
  { :name => "right-hand-facing-keyboard-return-for-desk", :title => "Right Hand Facing Keyboard Return for Desk", :created_at => "2013-08-07 00:37:25", :updated_at => "2013-08-08 17:03:06", :collection_id => 1, :skin_id => 2, :video => "", :features => "<ul>\r\n\t<li>Drop down keyboard/pencil drawer</li>\r\n\t<li>Wire management grommet</li>\r\n\t<li>One pencil drawer</li>\r\n\t<li>One utility drawer with dividers</li>\r\n\t<li>One locking letter/legal file drawer</li>\r\n</ul>\r\n", :active => true, :shown => false, :include_finish_name => false },
  { :name => "desk-for-right-hand-facing-keyboard-return", :title => "Desk for Right Hand Facing Keyboard Return", :created_at => "2013-08-07 00:40:13", :updated_at => "2013-08-07 00:40:13", :collection_id => 1, :skin_id => 2, :video => "", :features => "<ul>\r\n\t<li>Drop down keyboard/pencil drawer</li>\r\n\t<li>Wire management hole accommodates Charge &amp; Connect</li>\r\n\t<li>One pencil drawer</li>\r\n\t<li>One utility drawer with dividers</li>\r\n\t<li>One locking letter/legal file drawer</li>\r\n</ul>\r\n", :active => true, :shown => false, :include_finish_name => false },
  { :name => "credenza", :title => "Credenza", :created_at => "2013-08-07 00:45:17", :updated_at => "2013-08-07 00:45:17", :collection_id => 1, :skin_id => 2, :video => "", :features => "<ul>\r\n\t<li>Drop down keyboard/pencil drawer</li>\r\n\t<li>Wire management grommet</li>\r\n\t<li>Two utility drawers with dividers</li>\r\n\t<li>Two pencil drawers</li>\r\n\t<li>Two locking letter/legal file drawers</li>\r\n</ul>\r\n", :active => true, :shown => true, :include_finish_name => false },
  { :name => "double-pedestal-desk", :title => "Double Pedestal Desk", :created_at => "2013-08-07 00:48:48", :updated_at => "2013-08-07 00:48:48", :collection_id => 1, :skin_id => 2, :video => "", :features => "<ul>\r\n\t<li>Drop down keyboard/pencil drawer</li>\r\n\t<li>Two utility drawers with dividers</li>\r\n\t<li>Two pencil drawers</li>\r\n\t<li>Two locking letter/legal file drawers</li>\r\n\t<li>Two wire management grommets accommodate Charge &amp; Connect</li>\r\n</ul>\r\n", :active => true, :shown => true, :include_finish_name => false },
  { :name => "open-bookcase", :title => "Open Bookcase", :created_at => "2013-08-07 00:52:43", :updated_at => "2013-08-07 00:52:43", :collection_id => 1, :skin_id => 2, :video => "", :features => "<ul>\r\n\t<li>Three adjustable shelves</li>\r\n\t<li>One fixed shelf</li>\r\n\t<li>Center can light with 3 stage touch dimmer</li>\r\n</ul>\r\n", :active => true, :shown => true, :include_finish_name => false },
  { :name => "double-open-bookcase", :title => "Double Open Bookcase", :created_at => "2013-08-07 01:00:14", :updated_at => "2013-08-07 01:00:14", :collection_id => 1, :skin_id => 2, :video => "", :features => "<ul>\r\n\t<li>Four glass adjustable shelves</li>\r\n\t<li>Two center can lights with 3 stage touch dimmer</li>\r\n</ul>\r\n", :active => true, :shown => true, :include_finish_name => false },
  { :name => "space-saver-table", :title => "Space Saver Table", :created_at => "2013-08-08 15:37:11", :updated_at => "2013-08-08 15:40:24", :collection_id => 2, :skin_id => 2, :video => "", :features => "<ul>\r\n\t<li>Suitable for wireless speaker storage</li>\r\n\t<li>Comes with optional wood panel or speaker cloth for doors</li>\r\n\t<li>Finished on all sides</li>\r\n</ul>\r\n", :active => true, :shown => true, :include_finish_name => false },
  { :name => "end-table", :title => "End Table", :created_at => "2013-08-08 15:50:29", :updated_at => "2013-08-08 15:50:29", :collection_id => 2, :skin_id => 2, :video => "", :features => "<ul>\r\n\t<li>Suitable for wireless speaker storage</li>\r\n\t<li>Comes with optional wood panel or speaker cloth for doors</li>\r\n\t<li>Finished on all sides</li>\r\n</ul>\r\n", :active => true, :shown => true, :include_finish_name => false }
], :without_protection => true )



ProductComponent.create([
  { :created_at => "2013-08-06 22:13:25", :updated_at => "2013-08-06 22:13:25", :product_id => 1, :component_id => 26 },
  { :created_at => "2013-08-06 22:33:35", :updated_at => "2013-08-06 22:33:35", :product_id => 2, :component_id => 30 },
  { :created_at => "2013-08-06 22:38:00", :updated_at => "2013-08-06 22:38:00", :product_id => 3, :component_id => 23 },
  { :created_at => "2013-08-06 22:46:55", :updated_at => "2013-08-06 22:46:55", :product_id => 4, :component_id => 21 },
  { :created_at => "2013-08-07 00:28:42", :updated_at => "2013-08-07 00:28:42", :product_id => 5, :component_id => 21 },
  { :created_at => "2013-08-07 00:32:20", :updated_at => "2013-08-07 00:32:20", :product_id => 6, :component_id => 23 },
  { :created_at => "2013-08-07 00:37:25", :updated_at => "2013-08-07 00:37:25", :product_id => 7, :component_id => 21 },
  { :created_at => "2013-08-07 00:37:25", :updated_at => "2013-08-07 00:37:25", :product_id => 7, :component_id => 23 },
  { :created_at => "2013-08-07 00:40:13", :updated_at => "2013-08-07 00:40:13", :product_id => 8, :component_id => 21 },
  { :created_at => "2013-08-07 00:45:17", :updated_at => "2013-08-07 00:45:17", :product_id => 9, :component_id => 19 },
  { :created_at => "2013-08-07 00:48:48", :updated_at => "2013-08-07 00:48:48", :product_id => 10, :component_id => 20 },
  { :created_at => "2013-08-07 00:52:43", :updated_at => "2013-08-07 00:52:43", :product_id => 11, :component_id => 14 },
  { :created_at => "2013-08-07 01:00:14", :updated_at => "2013-08-07 01:00:14", :product_id => 12, :component_id => 14 },
  { :created_at => "2013-08-08 15:37:11", :updated_at => "2013-08-08 15:37:11", :product_id => 13, :component_id => 4 },
  { :created_at => "2013-08-08 15:50:29", :updated_at => "2013-08-08 15:50:29", :product_id => 14, :component_id => 4 }
], :without_protection => true )



Section.create([
  { :name => "resources", :title => "Resources", :created_at => "2013-08-05 18:33:14", :updated_at => "2013-08-05 18:33:14", :content => "", :parent_id => 0, :skin_id => 4 },
  { :name => "entertainment-solutions", :title => "Entertainment Solutions", :created_at => "2013-08-05 18:33:34", :updated_at => "2013-08-05 18:33:48", :content => "", :parent_id => 1, :skin_id => 4 },
  { :name => "easy-wire-access-system", :title => "Easy Wire Access System", :created_at => "2013-08-05 18:34:14", :updated_at => "2013-08-05 18:34:14", :content => "", :parent_id => 2, :skin_id => 4 },
  { :name => "entertainment-walls", :title => "Entertainment Walls", :created_at => "2013-08-05 18:34:43", :updated_at => "2013-08-05 18:34:43", :content => "", :parent_id => 2, :skin_id => 4 },
  { :name => "office-solutions", :title => "Office Solutions", :created_at => "2013-08-05 18:36:08", :updated_at => "2013-08-05 18:36:08", :content => "", :parent_id => 1, :skin_id => 4 },
  { :name => "modular-office", :title => "Modular Office", :created_at => "2013-08-05 18:36:49", :updated_at => "2013-08-05 18:36:49", :content => "", :parent_id => 5, :skin_id => 4 },
  { :name => "power-connectivity-centers", :title => "Power/Connectivity Centers", :created_at => "2013-08-05 18:37:09", :updated_at => "2013-08-05 18:37:09", :content => "", :parent_id => 5, :skin_id => 4 },
  { :name => "quality-craftsmanship", :title => "Quality Craftsmanship", :created_at => "2013-08-05 18:37:29", :updated_at => "2013-08-05 18:37:29", :content => "", :parent_id => 1, :skin_id => 4 },
  { :name => "distressing", :title => "Distressing", :created_at => "2013-08-05 18:37:51", :updated_at => "2013-08-05 18:37:51", :content => "", :parent_id => 8, :skin_id => 4 },
  { :name => "drawer-construction", :title => "Drawer Construction", :created_at => "2013-08-05 18:38:11", :updated_at => "2013-08-05 18:38:11", :content => "", :parent_id => 8, :skin_id => 4 },
  { :name => "videos", :title => "Videos", :created_at => "2013-08-05 18:38:29", :updated_at => "2013-08-05 18:38:29", :content => "", :parent_id => 1, :skin_id => 4 },
  { :name => "furniture-care", :title => "Furniture Care", :created_at => "2013-08-05 18:38:51", :updated_at => "2013-08-05 18:38:51", :content => "", :parent_id => 1, :skin_id => 4 },
  { :name => "warranty-information", :title => "Warranty Information", :created_at => "2013-08-05 18:39:13", :updated_at => "2013-08-05 18:39:13", :content => "", :parent_id => 1, :skin_id => 4 },
  { :name => "get-to-know-us", :title => "Get to Know Us", :created_at => "2013-08-05 18:39:29", :updated_at => "2013-08-05 18:39:29", :content => "", :parent_id => 0, :skin_id => 4 },
  { :name => "brand-info", :title => "Brand Info", :created_at => "2013-08-05 18:40:01", :updated_at => "2013-08-05 18:40:01", :content => "", :parent_id => 14, :skin_id => 4 },
  { :name => "mhf", :title => "MHF", :created_at => "2013-08-05 18:40:21", :updated_at => "2013-08-05 18:40:21", :content => "", :parent_id => 15, :skin_id => 4 },
  { :name => "kathy-ireland", :title => "Kathy Ireland", :created_at => "2013-08-05 18:40:38", :updated_at => "2013-08-05 18:40:38", :content => "", :parent_id => 15, :skin_id => 4 },
  { :name => "company", :title => "Company", :created_at => "2013-08-05 18:40:56", :updated_at => "2013-08-05 18:40:56", :content => "", :parent_id => 14, :skin_id => 4 },
  { :name => "sustainability-efforts", :title => "Sustainability Efforts", :created_at => "2013-08-05 18:41:20", :updated_at => "2013-08-05 18:41:20", :content => "", :parent_id => 14, :skin_id => 4 },
  { :name => "news-releases", :title => "News Releases", :created_at => "2013-08-05 18:41:42", :updated_at => "2013-08-05 18:41:42", :content => "", :parent_id => 14, :skin_id => 4 },
  { :name => "legal-privacy-policy", :title => "Legal/Privacy Policy", :created_at => "2013-08-05 18:42:12", :updated_at => "2013-08-05 18:42:12", :content => "", :parent_id => 14, :skin_id => 4 },
  { :name => "let-us-help", :title => "Let Us Help", :created_at => "2013-08-05 18:42:34", :updated_at => "2013-08-05 18:42:34", :content => "", :parent_id => 0, :skin_id => 4 },
  { :name => "contact-us", :title => "Contact Us", :created_at => "2013-08-05 18:43:08", :updated_at => "2013-08-05 18:43:08", :content => "", :parent_id => 22, :skin_id => 4 },
  { :name => "get-in-touch", :title => "Get In Touch", :created_at => "2013-08-05 18:43:40", :updated_at => "2013-08-16 22:26:39", :content => "", :parent_id => 23, :skin_id => 5 },
  { :name => "customer-satisfaction-department", :title => "Customer Satisfaction Department", :created_at => "2013-08-05 18:44:03", :updated_at => "2013-08-05 18:44:03", :content => "", :parent_id => 23, :skin_id => 4 },
  { :name => "media-marketing", :title => "Media & Marketing", :created_at => "2013-08-05 18:44:31", :updated_at => "2013-08-05 18:44:31", :content => "", :parent_id => 23, :skin_id => 4 },
  { :name => "parts-request", :title => "Parts Request", :created_at => "2013-08-05 18:45:03", :updated_at => "2013-08-05 18:45:03", :content => "", :parent_id => 23, :skin_id => 4 },
  { :name => "faq", :title => "FAQ", :created_at => "2013-08-05 18:46:33", :updated_at => "2013-08-05 18:46:33", :content => "", :parent_id => 22, :skin_id => 4 },
  { :name => "consumer-faq", :title => "Consumer FAQ", :created_at => "2013-08-05 18:46:57", :updated_at => "2013-08-05 18:46:57", :content => "", :parent_id => 28, :skin_id => 4 },
  { :name => "retailer-faq", :title => "Retailer FAQ", :created_at => "2013-08-05 18:47:16", :updated_at => "2013-08-05 18:47:16", :content => "", :parent_id => 28, :skin_id => 4 },
  { :name => "find-a-sales-rep", :title => "Find a Sales Rep", :created_at => "2013-08-05 18:47:44", :updated_at => "2013-08-05 18:47:44", :content => "", :parent_id => 22, :skin_id => 4 },
  { :name => "find-a-retailer", :title => "Find a Retailer", :created_at => "2013-08-05 18:49:43", :updated_at => "2013-08-05 18:49:43", :content => "", :parent_id => 22, :skin_id => 4 },
  { :name => "stay-connected", :title => "Stay Connected", :created_at => "2013-08-05 18:50:43", :updated_at => "2013-08-05 18:50:43", :content => "", :parent_id => 0, :skin_id => 4 },
  { :name => "pinterest", :title => "Pinterest", :created_at => "2013-08-05 18:51:21", :updated_at => "2013-08-05 18:51:21", :content => "", :parent_id => 33, :skin_id => 4 },
  { :name => "twitter", :title => "Twitter", :created_at => "2013-08-05 18:51:57", :updated_at => "2013-08-05 18:51:57", :content => "", :parent_id => 33, :skin_id => 4 },
  { :name => "youtube", :title => "YouTube", :created_at => "2013-08-05 18:52:19", :updated_at => "2013-08-05 18:52:19", :content => "", :parent_id => 33, :skin_id => 4 },
  { :name => "sales-reps-retailers", :title => "Sales Reps & Retailers", :created_at => "2013-08-05 18:52:45", :updated_at => "2013-08-05 18:53:04", :content => "", :parent_id => 0, :skin_id => 4 },
  { :name => "sales-rep-login", :title => "Sales Rep Login", :created_at => "2013-08-05 18:53:39", :updated_at => "2013-08-05 18:53:39", :content => "", :parent_id => 37, :skin_id => 4 },
  { :name => "esalesforce", :title => "eSalesForce", :created_at => "2013-08-05 18:54:06", :updated_at => "2013-08-05 18:54:06", :content => "", :parent_id => 38, :skin_id => 4 },
  { :name => "marketing-materials", :title => "Marketing Materials", :created_at => "2013-08-05 18:54:26", :updated_at => "2013-08-05 18:54:26", :content => "", :parent_id => 38, :skin_id => 4 },
  { :name => "commonly-used-forms", :title => "Commonly Used Forms", :created_at => "2013-08-05 18:55:01", :updated_at => "2013-08-05 18:55:01", :content => "", :parent_id => 38, :skin_id => 4 },
  { :name => "faq-sales-reps", :title => "FAQ - Sales Reps", :created_at => "2013-08-05 18:55:25", :updated_at => "2013-08-05 18:55:25", :content => "", :parent_id => 38, :skin_id => 4 },
  { :name => "retailer-login", :title => "Retailer Login", :created_at => "2013-08-05 18:55:52", :updated_at => "2013-08-05 18:55:52", :content => "", :parent_id => 37, :skin_id => 4 }
], :without_protection => true )



Skin.create([
  { :name => "compilation", :title => "Compilation", :template => "layouts/templates/compilation", :created_at => "2013-08-05 05:01:31", :updated_at => "2013-08-05 05:01:31" },
  { :name => "home", :title => "Home", :template => "layouts/templates/home", :created_at => "2013-08-05 05:00:47", :updated_at => "2013-08-05 05:00:47" },
  { :name => "product", :title => "Product", :template => "layouts/templates/product", :created_at => "2013-08-05 05:01:14", :updated_at => "2013-08-05 05:01:14" },
  { :name => "section", :title => "Section", :template => "layouts/templates/section", :created_at => "2013-08-05 05:01:46", :updated_at => "2013-08-05 05:01:46" },
  { :name => "section-blank", :title => "Section - Blank", :template => "layouts/templates/blank", :created_at => "2013-08-16 22:33:53", :updated_at => "2013-08-16 22:33:53" },
  { :name => "section-w-contact-form", :title => "Section w/Contact Form", :template => "layouts/templates/contact_form", :created_at => "2013-08-16 22:25:53", :updated_at => "2013-08-16 22:25:53" }
], :without_protection => true )



Sku.create([
  { :product_id => 1, :created_at => "2013-08-06 22:13:25", :updated_at => "2013-08-06 22:13:25", :finish_id => 20, :name => "bt450", :title => "BT450", :compilation_id => nil },
  { :product_id => 2, :created_at => "2013-08-06 22:33:35", :updated_at => "2013-08-06 22:33:35", :finish_id => 20, :name => "bt682", :title => "BT682", :compilation_id => nil },
  { :product_id => 3, :created_at => "2013-08-06 22:38:00", :updated_at => "2013-08-07 19:23:47", :finish_id => 20, :name => "bt684b", :title => "BT684B", :compilation_id => 2 },
  { :product_id => 4, :created_at => "2013-08-06 22:46:55", :updated_at => "2013-08-07 03:21:33", :finish_id => 20, :name => "bt684l-r", :title => "BT684L-R", :compilation_id => 1 },
  { :product_id => 5, :created_at => "2013-08-07 00:28:42", :updated_at => "2013-08-07 03:21:33", :finish_id => 20, :name => "bt684l", :title => "BT684L", :compilation_id => 1 },
  { :product_id => 6, :created_at => "2013-08-07 00:32:20", :updated_at => "2013-08-07 19:23:47", :finish_id => 20, :name => "bt684r-c", :title => "BT684R-C", :compilation_id => 2 },
  { :product_id => 7, :created_at => "2013-08-07 00:37:25", :updated_at => "2013-08-07 19:25:11", :finish_id => 20, :name => "bt684r-r", :title => "BT684R-R", :compilation_id => 3 },
  { :product_id => 8, :created_at => "2013-08-07 00:40:13", :updated_at => "2013-08-07 19:25:11", :finish_id => 20, :name => "bt684r", :title => "BT684R", :compilation_id => 3 },
  { :product_id => 9, :created_at => "2013-08-07 00:45:18", :updated_at => "2013-08-07 00:45:18", :finish_id => 20, :name => "bt689", :title => "BT689", :compilation_id => nil },
  { :product_id => 10, :created_at => "2013-08-07 00:48:48", :updated_at => "2013-08-07 00:48:48", :finish_id => 20, :name => "bt720", :title => "BT720", :compilation_id => nil },
  { :product_id => 11, :created_at => "2013-08-07 00:52:43", :updated_at => "2013-08-07 00:52:43", :finish_id => 20, :name => "bt3678", :title => "BT3678", :compilation_id => nil },
  { :product_id => 12, :created_at => "2013-08-07 01:00:14", :updated_at => "2013-08-07 01:00:14", :finish_id => 20, :name => "bt4678", :title => "BT4678", :compilation_id => nil },
  { :product_id => 13, :created_at => "2013-08-08 15:37:12", :updated_at => "2013-08-08 15:37:12", :finish_id => 22, :name => "imbr45", :title => "IMBR45", :compilation_id => nil },
  { :product_id => 14, :created_at => "2013-08-08 15:50:29", :updated_at => "2013-08-08 15:50:29", :finish_id => 22, :name => "imbr50", :title => "IMBR50", :compilation_id => nil }
], :without_protection => true )



Style.create([
  { :name => "americana", :title => "Americana", :created_at => "2013-08-05 05:47:49", :updated_at => "2013-08-07 19:27:28", :brand_id => 1, :description => "<p>Elegant, yet relaxed and steeped in the very best of our country&rsquo;s heritage, the Americana Style Guide&trade; offers rustic simplicity at its finest.&nbsp; Americana seeks to embody the diversity and rich traditions of our nation through the use of subtle distressing and inspiration from colors such as Yellow Corn, Green Grass and Wheatfield Brown.&nbsp; Unique and intricate detailing, the use of an eclectic array of materials and incredible durability are the cornerstones of this traditional style.</p>\r\n" },
  { :name => "architectural", :title => "Architectural", :created_at => "2013-08-05 05:48:23", :updated_at => "2013-08-07 19:27:45", :brand_id => 1, :description => "<p>This style is deeply influenced by clean lines, minimalism and simplicity; where form follows function.&nbsp; Understated colors with an emphasis on neutral tones combine to produce a sophisticated, appealing and comfortable style.&nbsp; Products inspired by this Style Guide&trade; are designed to mix easily with furnishings and accessories from other time periods to create an unmistakably modern feel with impeccable flair.</p>\r\n" },
  { :name => "contemporary", :title => "Contemporary", :created_at => "2013-08-05 05:49:02", :updated_at => "2013-08-05 05:52:14", :brand_id => 2, :description => "" },
  { :name => "mission", :title => "Mission", :created_at => "2013-08-05 05:49:31", :updated_at => "2013-08-05 05:52:14", :brand_id => 2, :description => "" },
  { :name => "traditional", :title => "Traditional", :created_at => "2013-08-05 05:49:54", :updated_at => "2013-08-05 05:52:14", :brand_id => 2, :description => "" },
  { :name => "transitional", :title => "Transitional", :created_at => "2013-08-05 05:50:37", :updated_at => "2013-08-05 05:52:14", :brand_id => 2, :description => "" }
], :without_protection => true )



User.create([
  { :email => "", :encrypted_password => "", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 0, :current_sign_in_at => nil, :last_sign_in_at => nil, :current_sign_in_ip => nil, :last_sign_in_ip => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )


